### ISSUE TITLE
No secrets files found.

### ISSUE THREAD

**Issue by ashraf133** [h9-tect/Chat_With_Github#1]
ashraf@ashrafs-Laptop Chat_With_Github % export GITHUB_TOKEN="XXXXXXXXX"
ashraf@ashrafs-Laptop Chat_With_Github % streamlit run app.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.1.15:8501

  For better performance, install the Watchdog module:

  $ xcode-select --install
  $ pip install watchdog

2024-06-21 23:29:33.501 Uncaught app exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
  File "/Users/ashraf/tests/Chat_With_Github/app.py", line 8, in <module>
    GITHUB_TOKEN = st.secrets.get("GITHUB_TOKEN", os.getenv("GITHUB_TOKEN"))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen _collections_abc>", line 774, in get
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/streamlit/runtime/secrets.py", line 305, in __getitem__
    value = self._parse(True)[key]
            ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/streamlit/runtime/secrets.py", line 214, in _parse
    raise FileNotFoundError(err_msg)
FileNotFoundError: No secrets files found. Valid paths for a secrets.toml file are: /Users/ashraf/.streamlit/secrets.toml, /Users/ashraf/tests/Chat_With_Github/.streamlit/secrets.toml

**Comment by h9-tect** [comment]
PLEASE FOLLOW THE INSTRUCTIONS ON README FILE
